# Generated by Django 4.0.3 on 2022-04-22 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_description', models.TextField()),
                ('event_snippet', models.CharField(max_length=25)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
    ]
