# Generated by Django 4.0.3 on 2022-04-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_availablerooms_id_alter_dateandslot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
