# Generated by Django 4.0.3 on 2022-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_room_price'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='dateandslot',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='dateandslot',
            name='room_price',
            field=models.IntegerField(default=3500),
        ),
        # migrations.AlterUniqueTogether(
        #     name='dateandslot',
        #     unique_together={('booking_date', 'booking_slot', 'room_price')},
        # ),
    ]
