# Generated by Django 4.0.3 on 2022-04-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_dateandslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateandslot',
            unique_together={('booking_date', 'booking_slot', 'room_price')},
        ),
    ]
