# Generated by Django 4.0.3 on 2022-04-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_dateandslot_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
