# Generated by Django 4.0.3 on 2022-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('manager', '0014_room_is_booked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Field',
        ),
    ]
