# Generated by Django 4.0.3 on 2022-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_room_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateandslot',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dateandslot',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash', max_length=20),
        ),
    ]
