# Generated by Django 4.0.3 on 2022-04-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_dateandslot_booking_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablerooms',
            old_name='rooms_available',
            new_name='fields_available',
        ),
        migrations.RenameField(
            model_name='dateandslot',
            old_name='room_price',
            new_name='booking_price',
        ),
        migrations.AlterUniqueTogether(
            name='dateandslot',
            unique_together={('booking_date', 'booking_slot', 'booking_price')},
        ),
    ]
