# Generated by Django 4.0.3 on 2022-04-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_rename_rooms_available_availablerooms_fields_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateandslot',
            name='booking_slot',
            field=models.CharField(choices=[('orning : 5 AM', 'Morning : 5 AM'), ('Morning : 7 AM', 'Morning : 7 AM'), ('Morning : 9 AM', 'Morning : 9 AM'), ('Morning : 11 AM', 'Morning : 11 AM'), ('Afternoon : 1 PM', 'Afternoon : 1 PM'), ('Afternoon : 3 PM', 'Afternoon : 3 PM'), ('Evening : 5 PM', 'Evening : 5 PM'), ('Evening : 7 PM', 'Evening : 7 PM'), ('Night : 5 PM', 'Night : 5 PM')], max_length=225),
        ),
    ]
